import type { AppBranding } from '../../../../config/branding.defaults';
import { StyleSheet } from 'react-native';
import { appShadow } from '../../../../styles/shadow';

function soft(hex: string, a = '22'): string {
  return /^#[0-9A-Fa-f]{6}$/.test(hex) ? `${hex}${a}` : hex;
}

export function createYoucamResultsStyles(
  colors: AppBranding['colors'],
  conventionScale = 1,
) {
  const s = (n: number) =>
    conventionScale === 1 ? n : Math.round(n * conventionScale);
  const tablet = conventionScale > 1;

  return StyleSheet.create({
    block: {
      gap: 12,
    },
    summaryRow: {
      gap: 6,
      paddingHorizontal: 2,
    },
    summaryLine: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    summaryMuted: {
      color: colors.muted,
      fontWeight: '600',
    },
    summaryAccent: {
      color: colors.primary,
      fontWeight: '800',
    },
    summaryPositive: {
      color: colors.success,
      fontWeight: '700',
    },
    summaryNeutral: {
      color: colors.muted,
      fontWeight: '700',
    },
    summaryAged: {
      color: colors.error,
      fontWeight: '700',
    },
    summaryMessage: {
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 18,
    },
    scoreBarBlock: {
      marginTop: 2,
      marginBottom: 4,
    },
    scoreBarLabels: {
      height: 16,
      position: 'relative',
      marginBottom: 2,
    },
    scoreBarValue: {
      position: 'absolute',
      top: 0,
      fontSize: 11,
      fontWeight: '800',
      color: colors.primary,
      transform: [{ translateX: -8 }],
    },
    scoreBarMax: {
      position: 'absolute',
      right: 0,
      top: 0,
      fontSize: 11,
      fontWeight: '800',
      color: colors.muted,
    },
    scoreBarTrack: {
      height: 8,
      borderRadius: 4,
      backgroundColor: '#E5E7EB',
      overflow: 'hidden',
    },
    scoreBarFill: {
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primary,
    },
    viewer: {
      width: '100%',
      aspectRatio: 0.85,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: '#F8FAFC',
      borderWidth: 1,
      borderColor: '#E5E7EB',
      position: 'relative',
    },
    viewerZoomLayer: {
      ...StyleSheet.absoluteFillObject,
    },
    viewerPanCatcher: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 1,
    },
    viewerImage: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
    },
    viewerOverlay: {
      ...StyleSheet.absoluteFill,
    },
    viewerBadge: {
      position: 'absolute',
      bottom: s(12),
      left: s(12),
      backgroundColor: colors.primary,
      borderRadius: 999,
      paddingHorizontal: s(12),
      paddingVertical: s(6),
      zIndex: 2,
    },
    zoomControls: {
      position: 'absolute',
      top: s(12),
      left: s(12),
      zIndex: 4,
      gap: 8,
    },
    zoomBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: 'rgba(255,255,255,0.92)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.08)',
    },
    zoomBtnDisabled: {
      opacity: 0.4,
    },
    zoomBtnText: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
      lineHeight: 24,
      marginTop: -1,
    },
    viewerBadgeText: {
      color: colors.textOnDark,
      fontSize: tablet ? s(12) + 3 : 14,
      fontWeight: '800',
    },
    conventionWrap: {
      position: 'absolute',
      right: s(2),
      top: s(48),
      width: tablet ? Math.max(s(54), 148) : 88,
      alignItems: 'flex-end',
      gap: s(3),
    },
    conventionBadge: {
      borderRadius: 999,
      paddingHorizontal: s(10),
      paddingVertical: s(5),
      maxWidth: tablet ? s(72) : 88,
    },
    conventionBadgeText: {
      color: '#FFFFFF',
      fontSize: tablet ? s(10) + 3 : 12,
      fontWeight: '800',
      textAlign: 'center',
    },
    conventionHigh: {
      color: '#FFFFFF',
      fontSize: tablet ? s(8) + 3 : 10,
      fontWeight: '700',
      textAlign: 'right',
      width: '100%',
      textShadowColor: 'rgba(0,0,0,0.55)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    conventionBar: {
      width: tablet ? s(10) : 14,
      height: tablet ? s(300) : 280,
      borderRadius: tablet ? s(5) : 7,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.45)',
      position: 'relative',
      alignSelf: 'flex-end',
    },
    conventionMarker: {
      position: 'absolute',
      left: -s(4),
      right: -s(4),
      height: s(4),
      borderRadius: s(2),
      backgroundColor: '#FFFFFF',
      borderWidth: 1.5,
      marginTop: -s(2),
    },
    conventionLow: {
      color: '#FFFFFF',
      fontSize: tablet ? s(8) + 3 : 10,
      fontWeight: '700',
      textAlign: 'right',
      width: '100%',
      textShadowColor: 'rgba(0,0,0,0.55)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    skinTypeConventionWrap: {
      position: 'absolute',
      right: s(6),
      top: s(8),
      bottom: s(8),
      width: s(72),
      justifyContent: 'space-between',
      alignItems: 'flex-end',
    },
    skinTypeConventionPanel: {
      backgroundColor: 'rgba(20, 20, 24, 0.5)',
      borderRadius: s(6),
      paddingHorizontal: s(5),
      paddingVertical: s(5),
      gap: s(4),
      width: s(64),
    },
    skinTypeMetricCol: {
      alignItems: 'center',
      gap: s(2),
    },
    skinTypeMetricLabel: {
      color: '#FFFFFF',
      fontSize: s(7),
      fontWeight: '700',
      textAlign: 'center',
    },
    skinTypeMetricBar: {
      width: '100%',
      height: s(14),
      borderRadius: s(2),
    },
    skinTypeLegendBox: {
      backgroundColor: 'rgba(235, 235, 238, 0.9)',
      borderWidth: 1,
      borderColor: 'rgba(30, 30, 30, 0.45)',
      borderRadius: s(3),
      paddingHorizontal: s(5),
      paddingVertical: s(4),
      gap: s(2),
      width: s(72),
    },
    skinTypeLegendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(4),
    },
    skinTypeLegendText: {
      color: '#111111',
      fontSize: s(7),
      fontWeight: '600',
      flexShrink: 1,
    },
    skinTypeZoneDash: {
      width: s(14),
      height: s(2),
      borderRadius: 1,
      backgroundColor: 'transparent',
      borderBottomWidth: 1.5,
      borderBottomColor: '#222222',
      borderStyle: 'dashed',
    },
    skinTypeZoneSolid: {
      width: s(14),
      height: conventionScale === 1 ? 1.5 : s(2),
      backgroundColor: '#222222',
      borderRadius: 1,
    },
    skinTypeZoneDashRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: conventionScale === 1 ? 1.5 : s(2),
    },
    skinTypeZoneDashSeg: {
      width: conventionScale === 1 ? 2.5 : s(3),
      height: conventionScale === 1 ? 1.5 : s(2),
      borderRadius: 1,
      backgroundColor: '#222222',
    },
    skinTypeDot: {
      width: s(6),
      height: s(6),
      borderRadius: s(3),
    },
    acneConventionWrap: {
      position: 'absolute',
      right: s(6),
      top: s(40),
      alignItems: 'flex-end',
    },
    acneConventionPanel: {
      backgroundColor: 'rgba(20, 20, 24, 0.45)',
      borderRadius: s(6),
      paddingHorizontal: s(5),
      paddingVertical: s(5),
      gap: s(5),
      width: s(92),
    },
    acneConventionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: s(5),
    },
    acneConventionLabel: {
      color: '#FFFFFF',
      fontSize: s(7),
      fontWeight: '700',
      textAlign: 'right',
      flexShrink: 1,
      textShadowColor: 'rgba(0,0,0,0.45)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    acneConventionBar: {
      width: s(10),
      height: s(22),
      borderRadius: s(2),
      flexShrink: 0,
    },
    catalogBlock: {
      gap: 10,
      marginTop: 4,
    },
    catalogTabBar: {
      backgroundColor: '#111827',
      borderRadius: 12,
      overflow: 'hidden',
    },
    catalogTabs: {
      flexDirection: 'row',
      gap: 4,
      padding: 4,
    },
    catalogTab: {
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    catalogTabOn: {
      backgroundColor: '#FFFFFF',
    },
    catalogTabText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#E5E7EB',
    },
    catalogTabTextOn: {
      color: '#111827',
    },
    catalogCards: {
      gap: 10,
      paddingVertical: 2,
    },
    catalogCard: {
      width: 132,
      borderRadius: 14,
      overflow: 'hidden',
      backgroundColor: '#111827',
      ...appShadow({ opacity: 0.1, radius: 8, offsetY: 2, elevation: 2 }),
    },
    catalogCardImage: {
      width: '100%',
      height: 120,
      backgroundColor: '#1F2937',
    },
    catalogCardImagePlaceholder: {
      width: '100%',
      height: 120,
      backgroundColor: soft(colors.primary, '33'),
      alignItems: 'center',
      justifyContent: 'center',
    },
    catalogCardPlaceholderText: {
      fontSize: 28,
      fontWeight: '800',
      color: colors.primary,
    },
    catalogCardFooter: {
      backgroundColor: colors.primary,
      paddingHorizontal: 8,
      paddingVertical: 8,
      minHeight: 44,
      justifyContent: 'center',
    },
    catalogCardTitle: {
      color: colors.textOnDark,
      fontSize: 11,
      fontWeight: '800',
      textAlign: 'center',
    },
    catalogEmpty: {
      fontSize: 12,
      lineHeight: 18,
      color: colors.muted,
      paddingHorizontal: 4,
    },
    recBlock: {
      marginTop: 4,
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#EEF0F3',
    },
    recToggle: {
      backgroundColor: colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    recToggleText: {
      color: colors.textOnDark,
      fontSize: 14,
      fontWeight: '800',
    },
    recLoading: {
      paddingVertical: 20,
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
    },
    recBody: {
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 8,
      gap: 18,
    },
    recSection: {
      gap: 10,
    },
    recSectionHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    recSectionTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    recSectionTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.text,
    },
    recSeeAll: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
    },
    recSectionActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    recHideBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 2,
      paddingHorizontal: 4,
    },
    recHideBtnText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.muted,
    },
    recoCardWrap: {
      position: 'relative',
    },
    recoCardHide: {
      position: 'absolute',
      top: 6,
      right: 6,
      zIndex: 2,
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: 'rgba(255,255,255,0.92)',
      borderWidth: 1,
      borderColor: '#E5E7EB',
      alignItems: 'center',
      justifyContent: 'center',
    },
    routineCardHide: {
      position: 'absolute',
      top: 8,
      right: 8,
      zIndex: 2,
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: 'rgba(255,255,255,0.92)',
      borderWidth: 1,
      borderColor: '#E5E7EB',
      alignItems: 'center',
      justifyContent: 'center',
    },
    recHiddenHint: {
      fontSize: 12,
      color: colors.muted,
      fontWeight: '600',
      paddingVertical: 4,
    },
    recRestoreLink: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
      marginTop: 4,
    },
    recCarousel: {
      gap: 10,
      paddingVertical: 2,
      paddingRight: 8,
    },
    routineCard: {
      width: 148,
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#EEF0F3',
      padding: 10,
      gap: 8,
      ...appShadow({ opacity: 0.06, radius: 8, offsetY: 2, elevation: 2 }),
    },
    routineCardOn: {
      borderColor: colors.primary,
      backgroundColor: soft(colors.primary, '10'),
    },
    recBadge: {
      alignSelf: 'flex-start',
      backgroundColor: colors.primary,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    recBadgeText: {
      color: colors.textOnDark,
      fontSize: 9,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    routineThumbs: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 56,
      paddingLeft: 4,
    },
    routineThumb: {
      width: 52,
      height: 52,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      backgroundColor: '#F3F4F6',
    },
    routineThumbEmpty: {
      width: '100%',
      height: 72,
      borderRadius: 12,
      backgroundColor: soft(colors.primary, '18'),
      alignItems: 'center',
      justifyContent: 'center',
    },
    routineCardTitle: {
      fontSize: 13,
      fontWeight: '800',
      color: colors.text,
    },
    routineCardMeta: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.muted,
    },
    routineDetail: {
      flexDirection: 'row',
      gap: 10,
      backgroundColor: '#F8FAFC',
      borderRadius: 14,
      padding: 12,
      borderWidth: 1,
      borderColor: '#EEF0F3',
    },
    routineDetailCopy: {
      flex: 1,
      gap: 8,
    },
    routineDetailText: {
      fontSize: 12,
      lineHeight: 18,
      color: colors.text,
    },
    routineMomentRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    routineMoment: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: '#FFFFFF',
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderWidth: 1,
      borderColor: soft(colors.primary, '33'),
    },
    routineMomentText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.primary,
    },
    routineSkinHint: {
      fontSize: 11,
      color: colors.muted,
      fontWeight: '600',
    },
    routineMediaCol: {
      width: 92,
      gap: 8,
    },
    routineMediaBtn: {
      width: 92,
      height: 72,
      borderRadius: 10,
      overflow: 'hidden',
      backgroundColor: '#E5E7EB',
    },
    routineMediaImg: {
      width: '100%',
      height: '100%',
    },
    routineMediaScrim: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 6,
      paddingVertical: 4,
      backgroundColor: 'rgba(0,0,0,0.45)',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    routineMediaLabel: {
      color: '#FFFFFF',
      fontSize: 9,
      fontWeight: '700',
      flex: 1,
    },
    recoCard: {
      width: 132,
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#EEF0F3',
      overflow: 'hidden',
      ...appShadow({ opacity: 0.06, radius: 8, offsetY: 2, elevation: 2 }),
    },
    recoCardTint: {
      backgroundColor: soft(colors.primary, '08'),
    },
    recoCardImage: {
      width: '100%',
      height: 110,
      backgroundColor: '#F3F4F6',
    },
    recoCardImagePlaceholder: {
      width: '100%',
      height: 110,
      backgroundColor: soft(colors.primary, '22'),
      alignItems: 'center',
      justifyContent: 'center',
    },
    recoCardTitle: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.text,
      paddingHorizontal: 8,
      paddingTop: 8,
    },
    recoCardSub: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.muted,
      paddingHorizontal: 8,
      paddingBottom: 10,
      paddingTop: 2,
    },
    viewerEmpty: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
    },
    viewerEmptyText: {
      color: '#E5E7EB',
      textAlign: 'center',
      fontSize: 13,
    },
    actionRow: {
      flexDirection: 'row',
      gap: 10,
    },
    actionBtn: {
      flex: 1,
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: 'center',
    },
    actionBtnText: {
      color: colors.textOnDark,
      fontWeight: '800',
      fontSize: 14,
    },
    scoreModeRow: {
      flexDirection: 'row',
      alignSelf: 'flex-start',
      backgroundColor: '#F3F4F6',
      borderRadius: 999,
      padding: 3,
      gap: 0,
    },
    scoreModeBtn: {
      borderRadius: 999,
      borderWidth: 0,
      backgroundColor: 'transparent',
      paddingHorizontal: 14,
      paddingVertical: 7,
    },
    scoreModeBtnOn: {
      borderColor: 'transparent',
      backgroundColor: colors.primary,
    },
    scoreModeText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.muted,
    },
    scoreModeTextOn: {
      color: colors.textOnDark,
    },
    regionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    regionPill: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    regionPillOn: {
      borderColor: colors.primary,
      backgroundColor: soft(colors.primary, '14'),
    },
    regionPillText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.muted,
    },
    regionPillTextOn: {
      color: colors.primary,
    },
    metricScroll: {
      marginHorizontal: -4,
    },
    metricChip: {
      width: 78,
      alignItems: 'center',
      gap: 6,
      marginHorizontal: 6,
    },
    metricRing: {
      width: 58,
      height: 58,
      borderRadius: 29,
      borderWidth: 3,
      borderColor: '#D1D5DB',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFFFFF',
      overflow: 'hidden',
    },
    metricRingActive: {
      borderColor: colors.primary,
      backgroundColor: soft(colors.primary, '14'),
    },
    metricRingScore: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
    },
    metricChipLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.muted,
      textAlign: 'center',
    },
    metricChipLabelActive: {
      color: colors.primary,
    },
    metricChipChevron: {
      marginTop: -2,
    },
    zonePanel: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#EEF0F3',
      overflow: 'hidden',
      ...appShadow({ opacity: 0.05, radius: 8, offsetY: 2, elevation: 1 }),
    },
    zonePanelHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: '#EEF0F3',
    },
    zonePanelTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.primary,
    },
    zoneRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: '#F3F4F6',
    },
    zoneRowOn: {
      backgroundColor: soft(colors.primary, '10'),
    },
    zoneRowCopy: {
      flex: 1,
      gap: 2,
    },
    zoneRowTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    zoneRowSub: {
      fontSize: 11,
      color: colors.muted,
      fontWeight: '500',
    },
    zoneRowValue: {
      fontSize: 13,
      fontWeight: '800',
      color: colors.text,
    },
    zoneDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    zoneFitzRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: soft(colors.primary, '08'),
    },
    copyCard: {
      backgroundColor: soft(colors.primary, '12'),
      borderRadius: 16,
      padding: 14,
      borderWidth: 1,
      borderColor: soft(colors.primary, '22'),
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    copyCardBody: {
      flex: 1,
      gap: 8,
    },
    copyText: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.text,
    },
    // Progress
    progressScreen: {
      flex: 1,
      backgroundColor: soft(colors.primary, '18'),
    },
    progressCard: {
      flex: 1,
      marginTop: 8,
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 24,
    },
    progressTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 12,
    },
    toggleRow: {
      flexDirection: 'row',
      alignSelf: 'center',
      backgroundColor: '#F3F4F6',
      borderRadius: 999,
      padding: 3,
      marginBottom: 12,
    },
    toggleBtn: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 999,
    },
    toggleBtnOn: {
      backgroundColor: colors.primary,
    },
    toggleText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.muted,
    },
    toggleTextOn: {
      color: colors.textOnDark,
    },
    legendRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 16,
      marginBottom: 14,
    },
    legendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    legendDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    legendText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.muted,
    },
    barRow: {
      marginBottom: 12,
    },
    barLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 6,
    },
    barPair: {
      gap: 4,
    },
    barTrack: {
      height: 12,
      borderRadius: 6,
      backgroundColor: '#F3F4F6',
      overflow: 'hidden',
    },
    barFill: {
      height: 12,
      borderRadius: 6,
    },
    barMeta: {
      fontSize: 11,
      color: colors.muted,
      marginTop: 2,
    },
    toggleHint: {
      fontSize: 12,
      color: colors.muted,
      textAlign: 'center',
      marginBottom: 12,
      paddingHorizontal: 8,
    },
    colChartScroll: {
      paddingBottom: 16,
    },
    colChartRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 10,
      paddingHorizontal: 4,
      minHeight: 220,
    },
    colItem: {
      width: 64,
      alignItems: 'center',
      gap: 6,
    },
    colBars: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'center',
      gap: 4,
      height: 140,
    },
    colBarTrack: {
      width: 18,
      height: 140,
      borderRadius: 6,
      backgroundColor: '#F3F4F6',
      justifyContent: 'flex-end',
      overflow: 'hidden',
    },
    colBarFill: {
      width: 18,
      borderRadius: 6,
    },
    colValue: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.muted,
    },
    colLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
      minHeight: 32,
    },
    note: {
      fontSize: 13,
      color: colors.muted,
      lineHeight: 18,
      backgroundColor: '#F9FAFB',
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
    },
    // Report
    reportActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
      marginBottom: 8,
    },
    reportActionBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#F3F4F6',
      alignItems: 'center',
      justifyContent: 'center',
    },
    reportTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 12,
    },
    reportHeader: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 14,
    },
    reportAvatar: {
      width: 72,
      height: 72,
      borderRadius: 12,
      backgroundColor: soft(colors.primary, '22'),
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
    },
    reportAvatarImg: {
      width: '100%',
      height: '100%',
    },
    reportMeta: {
      flex: 1,
      gap: 3,
      justifyContent: 'center',
    },
    reportMetaText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    reportMetaMuted: {
      fontSize: 12,
      color: colors.muted,
    },
    reportStats: {
      gap: 4,
      marginBottom: 12,
    },
    bandLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.primary,
      marginTop: 4,
    },
    rangeTrack: {
      height: 14,
      borderRadius: 7,
      flexDirection: 'row',
      overflow: 'hidden',
      marginTop: 8,
      marginBottom: 4,
    },
    rangeSeg: {
      height: 14,
    },
    rangeMarkerWrap: {
      height: 20,
      marginBottom: 12,
      position: 'relative',
    },
    rangeMarker: {
      position: 'absolute',
      top: 0,
      width: 22,
      height: 22,
      marginLeft: -11,
      borderRadius: 11,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    rangeMarkerText: {
      color: '#FFF',
      fontSize: 9,
      fontWeight: '800',
    },
    rangeLabels: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    rangeLabel: {
      fontSize: 11,
      fontWeight: '700',
    },
    summaryBox: {
      backgroundColor: '#F3F4F6',
      borderRadius: 12,
      padding: 12,
      marginBottom: 14,
    },
    summaryTitle: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.muted,
      marginBottom: 6,
      letterSpacing: 0.5,
    },
    summaryBody: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.text,
    },
    sectionHeading: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 10,
      marginTop: 4,
    },
    metricList: {
      gap: 12,
      paddingBottom: 24,
    },
    metricRowCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#EEF0F3',
      overflow: 'hidden',
      ...appShadow({ opacity: 0.04, radius: 6, offsetY: 2, elevation: 1 }),
    },
    metricRowTop: {
      flexDirection: 'row',
      padding: 12,
      gap: 12,
    },
    metricRowThumbWrap: {
      width: 88,
      height: 110,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: '#F3F4F6',
    },
    metricRowThumb: {
      width: '100%',
      height: '100%',
    },
    metricRowThumbEmpty: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    metricRowBody: {
      flex: 1,
      gap: 6,
    },
    metricRowHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
    },
    metricRowTitle: {
      flex: 1,
      fontSize: 15,
      fontWeight: '800',
      color: colors.text,
    },
    metricRowBand: {
      fontSize: 12,
      fontWeight: '700',
    },
    metricRowScoreRow: {
      alignItems: 'flex-start',
    },
    metricRowPin: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
      minWidth: 40,
      alignItems: 'center',
    },
    metricRowPinText: {
      color: '#FFFFFF',
      fontWeight: '800',
      fontSize: 13,
    },
    metricRowScale: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    metricRowScaleText: {
      fontSize: 10,
      color: colors.muted,
      fontWeight: '600',
    },
    metricAdviceBox: {
      backgroundColor: soft(colors.primary, '14'),
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    metricAdviceText: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.text,
      fontWeight: '500',
    },
    radarWrap: {
      alignItems: 'center',
      marginBottom: 16,
      paddingVertical: 8,
    },
    metricGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    metricCard: {
      width: '48%',
      flexGrow: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#EEF0F3',
      padding: 10,
      gap: 6,
      ...appShadow({ opacity: 0.03, radius: 4, offsetY: 1, elevation: 1 }),
    },
    metricCardTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.text,
    },
    metricCardBand: {
      fontSize: 11,
      fontWeight: '700',
    },
    metricCardTrack: {
      height: 8,
      borderRadius: 4,
      backgroundColor: '#F3F4F6',
      overflow: 'hidden',
    },
    metricCardFill: {
      height: 8,
      borderRadius: 4,
    },
    metricCardScore: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
    },
  });
}
