import type { AppBranding } from '../../../../config/branding.defaults';
import { StyleSheet } from 'react-native';
import { appShadow } from '../../../../styles/shadow';

function soft(hex: string, a = '22'): string {
  return /^#[0-9A-Fa-f]{6}$/.test(hex) ? `${hex}${a}` : hex;
}

export function createPatientDetailStyles(colors: AppBranding['colors']) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: soft(colors.primary, '18'),
    },
    card: {
      flex: 1,
      marginTop: 8,
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      overflow: 'hidden',
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 12,
    },
    roundBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#F3F4F6',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.muted,
    },
    identity: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 16,
      marginBottom: 16,
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 16,
      backgroundColor: '#FFFFFF',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: soft(colors.primary, '28'),
      ...appShadow({ opacity: 0.06, radius: 10, offsetY: 3, elevation: 2 }),
    },
    identityInfo: {
      flex: 1,
      minWidth: 0,
      gap: 6,
    },
    avatar: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: soft(colors.primary),
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      flexShrink: 0,
    },
    avatarImage: {
      width: '100%',
      height: '100%',
    },
    avatarText: {
      fontSize: 24,
      fontWeight: '800',
      color: colors.primary,
    },
    name: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.primaryDark,
      textAlign: 'left',
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    meta: {
      flexShrink: 1,
      fontSize: 13,
      color: colors.primary,
      textAlign: 'left',
      lineHeight: 18,
      fontWeight: '500',
    },
    dateSearchWrap: {
      marginTop: 0,
      marginBottom: 0,
      marginHorizontal: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E5E7EB',
      borderRadius: 999,
      paddingHorizontal: 16,
      paddingVertical: 13,
    },
    dateSearchInput: {
      flex: 1,
      fontSize: 14,
      color: colors.text,
      padding: 0,
      fontWeight: '600',
    },
    historyFilterRow: {
      paddingHorizontal: 16,
      paddingBottom: 4,
      gap: 10,
      flexDirection: 'row',
      alignItems: 'center',
    },
    historyFilterChip: {
      borderRadius: 999,
      paddingHorizontal: 16,
      paddingVertical: 9,
      backgroundColor: '#F3F4F6',
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    historyFilterChipOn: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    historyFilterChipText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.muted,
    },
    historyFilterChipTextOn: {
      color: colors.textOnDark,
    },
    newAnalysisSection: {
      marginTop: 16,
      alignSelf: 'stretch',
      gap: 14,
      paddingHorizontal: 16,
    },
    newAnalysisHint: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.primaryDark,
      textAlign: 'left',
      marginBottom: 2,
    },
    providerCards: {
      flexDirection: 'row',
      gap: 10,
      alignItems: 'stretch',
    },
    clinicalActions: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 10,
      marginTop: 2,
    },
    clinicalAction: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 999,
      paddingVertical: 12,
      paddingHorizontal: 12,
    },
    clinicalActionPrimary: {
      backgroundColor: colors.primary,
    },
    clinicalActionSecondary: {
      backgroundColor: '#FFFFFF',
      borderWidth: 1.5,
      borderColor: colors.primary,
    },
    clinicalActionPrimaryText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textOnDark,
    },
    clinicalActionSecondaryText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
    },
    providerCard: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 16,
      borderWidth: 1,
      paddingVertical: 14,
      paddingHorizontal: 10,
    },
    providerCardIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    providerCardTextCol: {
      width: '100%',
      alignItems: 'center',
      gap: 2,
    },
    providerCardText: {
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 15,
      textAlign: 'center',
    },
    providerEmpty: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 12,
      backgroundColor: '#F3F4F6',
    },
    providerEmptyText: {
      fontSize: 13,
      color: colors.muted,
      textAlign: 'left',
      fontWeight: '600',
      lineHeight: 18,
    },
    providerScroll: {
      marginHorizontal: -4,
    },
    providerScrollContent: {
      paddingHorizontal: 4,
      gap: 8,
      alignItems: 'center',
    },
    providerPill: {
      backgroundColor: colors.primary,
      borderRadius: 999,
      paddingVertical: 12,
      paddingHorizontal: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    providerPillText: {
      color: colors.textOnDark,
      fontWeight: '700',
      fontSize: 13,
    },
    newAnalysisBtn: {
      marginTop: 12,
      alignSelf: 'stretch',
      marginHorizontal: 24,
      backgroundColor: colors.primary,
      borderRadius: 999,
      paddingVertical: 14,
      paddingHorizontal: 24,
      alignItems: 'center',
    },
    newAnalysisText: {
      color: colors.textOnDark,
      fontWeight: '700',
      fontSize: 15,
    },
    pendingCancelBtn: {
      minHeight: 40,
      minWidth: 84,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: '#EF4444',
      backgroundColor: '#FEF2F2',
      alignItems: 'center',
      justifyContent: 'center',
    },
    pendingCancelText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#EF4444',
    },
    historyHeader: {
      marginTop: 22,
      marginBottom: 6,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      gap: 12,
    },
    historyTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.primaryDark,
      flexShrink: 1,
    },
    historyActions: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      gap: 8,
      flexShrink: 1,
    },
    historyActionPrimary: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.primary,
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 12,
    },
    historyActionPrimaryText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textOnDark,
    },
    historyActionSecondary: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'transparent',
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: colors.primary,
      paddingVertical: 8,
      paddingHorizontal: 14,
    },
    historyActionSecondaryText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
    },
    requestOverlay: {
      flex: 1,
      backgroundColor: 'rgba(15, 23, 42, 0.45)',
      justifyContent: 'flex-end',
    },
    requestSheet: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 16,
      paddingTop: 18,
      paddingBottom: 28,
      gap: 10,
    },
    requestSheetTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.primaryDark,
    },
    requestSheetSubtitle: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.muted,
      marginBottom: 4,
    },
    requestOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: 14,
      borderWidth: 1,
      paddingVertical: 12,
      paddingHorizontal: 12,
    },
    requestOptionIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    requestOptionText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
    },
    requestCancel: {
      alignItems: 'center',
      paddingVertical: 12,
      marginTop: 2,
    },
    requestCancelText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.muted,
    },
    historyAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    historyActionText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.primary,
    },
    list: {
      flex: 1,
    },
    listContent: {
      paddingTop: 4,
      paddingBottom: 36,
      flexGrow: 1,
    },
    analysisRow: {
      marginHorizontal: 16,
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: soft(colors.primary, '28'),
      paddingVertical: 14,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    kindIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    thumb: {
      width: 56,
      height: 56,
      borderRadius: 10,
      backgroundColor: soft(colors.primary),
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    thumbImage: {
      width: 56,
      height: 56,
    },
    analysisBody: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    analysisTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    analysisTitle: {
      flex: 1,
      minWidth: 0,
      fontSize: 14,
      fontWeight: '800',
      color: colors.primaryDark,
    },
    differential: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.primary,
    },
    metaBadges: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 6,
    },
    typeBadge: {
      maxWidth: '70%',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: '#D1D5DB',
      backgroundColor: '#F9FAFB',
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    typeBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.text,
    },
    statusBadge: {
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 3,
      flexShrink: 0,
    },
    statusBadgeInvalid: {
      backgroundColor: soft(colors.error, '18'),
    },
    statusBadgeConfirmed: {
      backgroundColor: soft(colors.primary, '18'),
    },
    statusBadgeCorrected: {
      backgroundColor: soft(colors.secondary, '22'),
    },
    statusBadgePending: {
      backgroundColor: '#F3F4F6',
    },
    statusBadgeDone: {
      backgroundColor: '#DCFCE7',
    },
    statusBadgeProgress: {
      backgroundColor: soft(colors.primary, '18'),
    },
    statusBadgeText: {
      fontSize: 11,
      fontWeight: '700',
    },
    statusBadgeTextInvalid: {
      color: colors.error,
    },
    statusBadgeTextConfirmed: {
      color: colors.primary,
    },
    statusBadgeTextCorrected: {
      color: colors.secondary,
    },
    statusBadgeTextPending: {
      color: colors.muted,
    },
    statusBadgeTextDone: {
      color: '#15803D',
    },
    statusBadgeTextProgress: {
      color: colors.primary,
    },
    diagnosis: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    regionLine: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.muted,
    },
    stampRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 1,
    },
    stamp: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '500',
    },
    goBtn: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    empty: {
      paddingVertical: 28,
      alignItems: 'center',
    },
    emptyText: {
      color: colors.muted,
      fontSize: 14,
      textAlign: 'center',
    },
    loading: {
      paddingVertical: 40,
      alignItems: 'center',
    },
  });
}

export type PatientDetailStyles = ReturnType<typeof createPatientDetailStyles>;
