-- AlterTable
ALTER TABLE "plans"
  ADD COLUMN IF NOT EXISTS "max_users" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "modules" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "role_limits" JSONB NOT NULL DEFAULT '{}';
