/**
 * Catálogo de iconos Iconify usados en la app.
 * Cualquier icono nuevo debe añadirse también en `babel.config.js`
 * (plugin `react-native-iconify/babel`).
 */
export const Icons = {
  home: 'mdi:home',
  calendar: 'mdi:calendar-month',
  chat: 'mdi:message-text',
  account: 'mdi:account',
  search: 'mdi:magnify',
  gift: 'mdi:gift-outline',
  menu: 'mdi:menu',
  back: 'mdi:chevron-left',
  chevronRight: 'mdi:chevron-right',
  edit: 'mdi:pencil',
  plus: 'mdi:plus',
  video: 'mdi:video-outline',
  moreVertical: 'mdi:dots-vertical',
  paperclip: 'mdi:paperclip',
  send: 'mdi:send',
  download: 'mdi:download',
  checkAll: 'mdi:check-all',
  check: 'mdi:check',
  clock: 'mdi:clock-outline',
  robot: 'mdi:robot-outline',
  mail: 'mdi:email-outline',
  skin: 'mdi:face-man-outline',
  phone: 'mdi:phone-outline',
  doc: 'mdi:card-account-details-outline',
  calendarDay: 'mdi:calendar',
  homeOutline: 'mdi:home-outline',
  paw: 'mdi:paw',
  dog: 'mdi:dog',
  cat: 'mdi:cat',
  settings: 'mdi:tune-variant',
  translate: 'mdi:translate',
  creditCard: 'mdi:credit-card-outline',
  share: 'mdi:share-variant-outline',
  lock: 'mdi:lock-outline',
  password: 'mdi:form-textbox-password',
  file: 'mdi:file-document-outline',
  support: 'mdi:headset',
  logout: 'mdi:logout',
  prescription: 'mdi:prescription',
  clipboard: 'mdi:clipboard-text-outline',
  smile: 'mdi:emoticon-happy-outline',
  sad: 'mdi:emoticon-sad-outline',
  document: 'mdi:file-document',
  nosology: 'mdi:clipboard-text-outline',
  close: 'mdi:close',
  calendarClock: 'mdi:calendar-clock',
  image: 'mdi:image-outline',
  google: 'mdi:google',
  eye: 'mdi:eye-outline',
  eyeOff: 'mdi:eye-off-outline',
  checkboxOn: 'mdi:checkbox-marked',
  checkboxOff: 'mdi:checkbox-blank-outline',
  mapMarker: 'mdi:map-marker-outline',
  bell: 'mdi:bell-outline',
  heartPulse: 'mdi:heart-pulse',
  clipboardCheck: 'mdi:clipboard-check-outline',
  accountGroup: 'mdi:account-group-outline',
} as const;

export type AppIconName = (typeof Icons)[keyof typeof Icons];

/** Lista para babel (debe coincidir con `Icons`). */
export const ICONIFY_BABEL_ICONS = Object.values(Icons);
