import type { AppBranding } from '../../../../config/branding.defaults';
import { StyleSheet } from 'react-native';

export function createRegisterStyles(colors: AppBranding['colors']) {
  return StyleSheet.create({
    safe: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      justifyContent: 'flex-end',
      paddingHorizontal: 24,
      paddingBottom: 28,
      paddingTop: 16,
    },
    scrollContentCard: {
      flexGrow: 1,
      justifyContent: 'flex-start',
      paddingHorizontal: 16,
      paddingBottom: 28,
      paddingTop: 12,
    },
    brand: {
      fontSize: 36,
      fontWeight: '700',
      color: colors.textOnDark,
      letterSpacing: -0.5,
      marginBottom: 6,
    },
    welcomeBanner: {
      backgroundColor: 'rgba(255,255,255,0.14)',
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 18,
    },
    welcomeBannerCard: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 18,
    },
    welcomeTitle: {
      color: colors.textOnDark,
      fontSize: 18,
      fontWeight: '800',
      marginBottom: 4,
    },
    welcomeSubtitle: {
      color: 'rgba(255,255,255,0.82)',
      fontSize: 14,
      lineHeight: 20,
    },
    subtitle: {
      fontSize: 15,
      lineHeight: 21,
      color: 'rgba(255,255,255,0.82)',
      marginBottom: 22,
      maxWidth: 320,
    },
    stepHint: {
      color: 'rgba(255,255,255,0.65)',
      fontSize: 12,
      fontWeight: '600',
      marginBottom: 12,
      letterSpacing: 0.4,
    },
    stepHintDark: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '600',
      marginBottom: 12,
      letterSpacing: 0.4,
    },
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: 28,
      paddingHorizontal: 18,
      paddingVertical: 20,
      marginTop: 8,
    },
    row: {
      flexDirection: 'row',
      gap: 10,
    },
    half: {
      flex: 1,
    },
    areaCode: {
      width: 96,
    },
    phoneFlex: {
      flex: 1,
    },
    field: {
      marginBottom: 12,
    },
    labelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    label: {
      color: 'rgba(255,255,255,0.78)',
      fontSize: 13,
      marginBottom: 6,
      fontWeight: '500',
    },
    labelDark: {
      color: colors.primaryDark,
      fontSize: 13,
      marginBottom: 6,
      fontWeight: '600',
    },
    labelInline: {
      color: 'rgba(255,255,255,0.78)',
      fontSize: 13,
      fontWeight: '500',
    },
    labelInlineDark: {
      color: colors.primaryDark,
      fontSize: 13,
      fontWeight: '600',
    },
    allowLink: {
      color: colors.textOnDark,
      fontSize: 13,
      fontWeight: '700',
      textDecorationLine: 'underline',
    },
    allowLinkDark: {
      color: colors.secondary,
      fontSize: 13,
      fontWeight: '700',
      textDecorationLine: 'underline',
    },
    whyLink: {
      color: 'rgba(255,255,255,0.9)',
      fontSize: 13,
      fontWeight: '600',
      textDecorationLine: 'underline',
      marginTop: 4,
      marginBottom: 8,
    },
    whyLinkDark: {
      color: colors.secondary,
      fontSize: 13,
      fontWeight: '600',
      textDecorationLine: 'underline',
      marginTop: 4,
      marginBottom: 8,
    },
    chips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 4,
    },
    chip: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.35)',
      paddingVertical: 10,
      paddingHorizontal: 12,
      backgroundColor: 'rgba(255,255,255,0.08)',
    },
    chipDark: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      paddingVertical: 10,
      paddingHorizontal: 12,
      backgroundColor: '#F9FAFB',
    },
    chipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    chipText: {
      color: 'rgba(255,255,255,0.85)',
      fontSize: 13,
      fontWeight: '600',
    },
    chipTextDark: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
    },
    chipTextActive: {
      color: colors.textOnDark,
    },
    input: {
      backgroundColor: colors.inputBackground,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      color: colors.text,
    },
    inputCard: {
      backgroundColor: '#F9FAFB',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      color: colors.text,
    },
    inputWithIcon: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderRadius: 14,
      paddingRight: 12,
    },
    inputWithIconCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F9FAFB',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      paddingRight: 12,
    },
    inputFlex: {
      flex: 1,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      color: colors.text,
    },
    error: {
      color: '#FECACA',
      fontSize: 14,
      marginBottom: 12,
      marginTop: 4,
    },
    errorDark: {
      color: colors.error,
      fontSize: 14,
      marginBottom: 12,
      marginTop: 4,
    },
    button: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 16,
      alignItems: 'center',
      marginTop: 8,
      flex: 1,
    },
    buttonSecondary: {
      backgroundColor: 'rgba(255,255,255,0.18)',
      borderRadius: 14,
      paddingVertical: 16,
      alignItems: 'center',
      marginTop: 8,
      flex: 1,
    },
    buttonSecondaryCard: {
      backgroundColor: colors.secondary,
      borderRadius: 14,
      paddingVertical: 16,
      alignItems: 'center',
      marginTop: 8,
      flex: 1,
    },
    buttonDisabled: {
      opacity: 0.65,
    },
    buttonText: {
      color: colors.textOnDark,
      fontSize: 16,
      fontWeight: '700',
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 4,
    },
    footer: {
      marginTop: 18,
      textAlign: 'center',
      color: 'rgba(255,255,255,0.75)',
      fontSize: 14,
    },
    footerRow: {
      marginTop: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    link: {
      color: colors.textOnDark,
      fontWeight: '700',
      textDecorationLine: 'underline',
    },
    footerLink: {
      color: 'rgba(255,255,255,0.9)',
      fontSize: 14,
      fontWeight: '600',
      textDecorationLine: 'underline',
      flexShrink: 1,
    },
    footerLinkDark: {
      color: colors.secondary,
      fontSize: 14,
      fontWeight: '600',
      textDecorationLine: 'underline',
      flexShrink: 1,
    },
    // Survey intro
    skinIntro: {
      backgroundColor: colors.secondary,
      borderRadius: 28,
      paddingHorizontal: 24,
      paddingVertical: 48,
      minHeight: 420,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      marginTop: 8,
    },
    skinIntroDecor: {
      ...StyleSheet.absoluteFillObject,
    },
    skinIntroBlob: {
      position: 'absolute',
      borderRadius: 999,
      backgroundColor: colors.textOnDark,
    },
    skinIntroTitle: {
      color: colors.textOnDark,
      fontSize: 26,
      fontWeight: '800',
      textAlign: 'center',
      lineHeight: 34,
      marginBottom: 12,
      paddingHorizontal: 8,
    },
    skinIntroSubtitle: {
      color: 'rgba(255,255,255,0.9)',
      fontSize: 15,
      textAlign: 'center',
      marginBottom: 36,
    },
    skinIntroButton: {
      backgroundColor: colors.textOnDark,
      borderRadius: 999,
      paddingVertical: 16,
      paddingHorizontal: 48,
      minWidth: 200,
      alignItems: 'center',
    },
    skinIntroButtonText: {
      color: colors.primaryDark,
      fontSize: 17,
      fontWeight: '800',
    },
    // Survey step
    progressDots: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 14,
      paddingHorizontal: 8,
      backgroundColor: 'rgba(255,255,255,0.92)',
      borderRadius: 16,
      marginBottom: 12,
    },
    progressDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: '#D1D5DB',
    },
    progressDotActive: {
      backgroundColor: colors.primary,
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    surveyQuestion: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
      marginBottom: 16,
      lineHeight: 26,
    },
    surveyHint: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 20,
      marginTop: 10,
      marginBottom: 4,
      backgroundColor: '#F3F4F6',
      borderRadius: 12,
      padding: 12,
    },
    optionList: {
      gap: 10,
      marginBottom: 8,
    },
    optionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#F3F4F6',
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: 'transparent',
      gap: 12,
    },
    optionRowActive: {
      borderColor: colors.primary,
      backgroundColor: 'rgba(108, 78, 227, 0.08)',
    },
    optionRowContent: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    optionLabel: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
    },
    optionLabelActive: {
      fontWeight: '700',
    },
    fitzSwatch: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.12)',
    },
    radioOuter: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: '#9CA3AF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioOuterActive: {
      borderColor: colors.primary,
    },
    radioInner: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.primary,
    },
  });
}

export type RegisterStyles = ReturnType<typeof createRegisterStyles>;
