import {
  BarChart3,
  Building2,
  CheckCircle2,
  ClipboardCheck,
  CreditCard,
  FileBarChart2,
  Gift,
  Globe2,
  HelpCircle,
  Home,
  Layers,
  Map,
  Package,
  Receipt,
  Settings,
  Shield,
  ShoppingCart,
  Bell,
  Users,
  Stethoscope,
  UserRound,
  UserCog,
  XCircle,
  GraduationCap,
  Briefcase,
} from "lucide-react";
import type { NavItem } from "@/components/layout/nav-items";
import { adminNavPermission } from "@/lib/admin-panel-permissions";

/** Nav del backoffice — visibilidad por slug de componente en BD (`permissions`). */
export const adminNav: NavItem[] = [
  {
    label: "Panel de control",
    href: "/admin",
    icon: Home,
    permissionsAny: adminNavPermission("/admin"),
  },
  {
    label: "Verificación (Pendientes)",
    href: "/admin/verificacion",
    icon: ClipboardCheck,
    permissionsAny: adminNavPermission("/admin/verificacion"),
    badgeKey: "pending-verification",
  },
  {
    label: "Verificados",
    href: "/admin/verificacion/verificados",
    icon: CheckCircle2,
    permissionsAny: adminNavPermission("/admin/verificacion/verificados"),
  },
  {
    label: "Rechazados",
    href: "/admin/verificacion/rechazados",
    icon: XCircle,
    permissionsAny: adminNavPermission("/admin/verificacion/rechazados"),
  },
  {
    label: "Moderadores",
    href: "/admin/moderadores",
    icon: UserCog,
    permissionsAny: adminNavPermission("/admin/moderadores"),
  },
  {
    label: "Mapas",
    href: "/admin/mapa",
    icon: Map,
    permissionsAny: adminNavPermission("/admin/mapa"),
    children: [
      {
        label: "Médicos",
        href: "/admin/mapa/medicos",
        icon: Stethoscope,
        permissionsAny: adminNavPermission("/admin/mapa/medicos"),
      },
      {
        label: "Pacientes",
        href: "/admin/mapa/pacientes",
        icon: UserRound,
        permissionsAny: adminNavPermission("/admin/mapa/pacientes"),
      },
    ],
  },
  {
    label: "Empresas",
    href: "/admin/empresas",
    icon: Building2,
    permissionsAny: adminNavPermission("/admin/empresas"),
  },
  {
    label: "Usuarios",
    href: "/admin/usuarios",
    icon: Users,
    permissionsAny: adminNavPermission("/admin/usuarios"),
  },
  {
    label: "Bolsa de unidades",
    href: "/admin/bolsa-unidades",
    icon: Package,
    permissionsAny: adminNavPermission("/admin/bolsa-unidades"),
  },
  {
    label: "Planes",
    href: "/admin/planes",
    icon: Layers,
    permissionsAny: adminNavPermission("/admin/planes"),
  },
  {
    label: "Compras y transacciones",
    href: "/admin/compras",
    icon: ShoppingCart,
    permissionsAny: adminNavPermission("/admin/compras"),
  },
  {
    label: "Reportes",
    href: "/admin/reportes",
    icon: FileBarChart2,
    permissionsAny: adminNavPermission("/admin/reportes"),
  },
  {
    label: "Facturación",
    href: "/admin/facturacion",
    icon: Receipt,
    permissionsAny: adminNavPermission("/admin/facturacion"),
  },
  {
    label: "Doctores",
    href: "/admin/doctores",
    icon: Stethoscope,
    permissionsAny: adminNavPermission("/admin/doctores"),
  },
  {
    label: "Pacientes",
    href: "/admin/pacientes",
    icon: UserRound,
    permissionsAny: adminNavPermission("/admin/pacientes"),
  },
  {
    label: "Suscripciones",
    href: "/admin/suscripciones",
    icon: CreditCard,
    permissionsAny: adminNavPermission("/admin/suscripciones"),
  },
  {
    label: "Consumo de análisis",
    href: "/admin/consumo",
    icon: BarChart3,
    permissionsAny: adminNavPermission("/admin/consumo"),
  },
  {
    label: "Configuración",
    href: "/admin/configuracion",
    icon: Settings,
    permissionsAny: adminNavPermission("/admin/configuracion"),
    children: [
      {
        label: "Profesionales",
        href: "/admin/especialidades",
        icon: Briefcase,
        permissionsAny: adminNavPermission("/admin/especialidades"),
        children: [
          {
            label: "Especialidades",
            href: "/admin/especialidades",
            icon: GraduationCap,
            permissionsAny: adminNavPermission("/admin/especialidades"),
          },
          {
            label: "Técnicos",
            href: "/admin/tecnico-laboral",
            icon: UserRound,
            permissionsAny: adminNavPermission("/admin/tecnico-laboral"),
          },
        ],
      },
      {
        label: "Roles y permisos",
        href: "/admin/roles",
        icon: Shield,
        permissionsAny: adminNavPermission("/admin/roles"),
      },
      {
        label: "Equipos",
        href: "/admin/configuracion/equipos",
        icon: Users,
        permissionsAny: adminNavPermission("/admin/configuracion/equipos"),
      },
      {
        label: "Referidos",
        href: "/admin/configuracion/referidos",
        icon: Gift,
        permissionsAny: adminNavPermission("/admin/configuracion/referidos"),
      },
      {
        label: "Global",
        href: "/admin/configuracion",
        icon: Globe2,
        permissionsAny: adminNavPermission("/admin/configuracion"),
      },
    ],
  },
  {
    label: "Auditoría",
    href: "/admin/auditoria",
    icon: Shield,
    permissionsAny: adminNavPermission("/admin/auditoria"),
  },
  {
    label: "Notificaciones",
    href: "/admin/notificaciones",
    icon: Bell,
    permissionsAny: adminNavPermission("/admin/notificaciones"),
  },
  {
    label: "Ayuda",
    href: "/admin/ayuda",
    icon: HelpCircle,
    permissionsAny: adminNavPermission("/admin/ayuda"),
  },
];
