import {
  BarChart3,
  Building2,
  CheckCircle2,
  ClipboardCheck,
  CreditCard,
  FileBarChart2,
  Gift,
  Globe2,
  HelpCircle,
  Home,
  Layers,
  Map,
  Package,
  Receipt,
  Settings,
  Shield,
  ShoppingCart,
  Bell,
  Users,
  Stethoscope,
  UserRound,
  UserCog,
  XCircle,
  GraduationCap,
  Briefcase,
} from "lucide-react";
import type { NavItem } from "@/components/layout/nav-items";
import { adminNavPermission } from "@/lib/admin-panel-permissions";

/** Nav del backoffice — visibilidad por slug de componente en BD (`permissions`). */
export const adminNav: NavItem[] = [
  {
    label: "Panel de control",
    href: "/admin",
    icon: Home,
    permissionsAny: adminNavPermission("admin.dashboard"),
  },
  {
    label: "Verificación (Pendientes)",
    href: "/admin/verificacion",
    icon: ClipboardCheck,
    permissionsAny: adminNavPermission("admin.verification.pending"),
    badgeKey: "pending-verification",
  },
  {
    label: "Verificados",
    href: "/admin/verificacion/verificados",
    icon: CheckCircle2,
    permissionsAny: adminNavPermission("admin.verification.verified"),
  },
  {
    label: "Rechazados",
    href: "/admin/verificacion/rechazados",
    icon: XCircle,
    permissionsAny: adminNavPermission("admin.verification.rejected"),
  },
  {
    label: "Moderadores",
    href: "/admin/moderadores",
    icon: UserCog,
    permissionsAny: adminNavPermission("admin.moderators"),
  },
  {
    label: "Mapas",
    href: "/admin/mapa",
    icon: Map,
    permissionsAny: adminNavPermission("admin.maps"),
    children: [
      {
        label: "Médicos",
        href: "/admin/mapa/medicos",
        icon: Stethoscope,
        permissionsAny: adminNavPermission("admin.maps.doctors"),
      },
      {
        label: "Pacientes",
        href: "/admin/mapa/pacientes",
        icon: UserRound,
        permissionsAny: adminNavPermission("admin.maps.patients"),
      },
    ],
  },
  {
    label: "Empresas",
    href: "/admin/empresas",
    icon: Building2,
    permissionsAny: adminNavPermission("admin.companies"),
  },
  {
    label: "Usuarios",
    href: "/admin/usuarios",
    icon: Users,
    permissionsAny: adminNavPermission("admin.users"),
  },
  {
    label: "Bolsa de unidades",
    href: "/admin/bolsa-unidades",
    icon: Package,
    permissionsAny: adminNavPermission("admin.unit_wallet"),
  },
  {
    label: "Planes",
    href: "/admin/planes",
    icon: Layers,
    permissionsAny: adminNavPermission("admin.plans"),
  },
  {
    label: "Compras y transacciones",
    href: "/admin/compras",
    icon: ShoppingCart,
    permissionsAny: adminNavPermission("admin.purchases"),
  },
  {
    label: "Reportes",
    href: "/admin/reportes",
    icon: FileBarChart2,
    permissionsAny: adminNavPermission("admin.reports"),
  },
  {
    label: "Facturación",
    href: "/admin/facturacion",
    icon: Receipt,
    permissionsAny: adminNavPermission("admin.billing"),
  },
  {
    label: "Doctores",
    href: "/admin/doctores",
    icon: Stethoscope,
    permissionsAny: adminNavPermission("admin.doctors"),
  },
  {
    label: "Pacientes",
    href: "/admin/pacientes",
    icon: UserRound,
    permissionsAny: adminNavPermission("admin.patients"),
  },
  {
    label: "Suscripciones",
    href: "/admin/suscripciones",
    icon: CreditCard,
    permissionsAny: adminNavPermission("admin.subscriptions"),
  },
  {
    label: "Consumo de análisis",
    href: "/admin/consumo",
    icon: BarChart3,
    permissionsAny: adminNavPermission("admin.analysis_consumption"),
  },
  {
    label: "Configuración",
    href: "/admin/configuracion",
    icon: Settings,
    permissionsAny: adminNavPermission("admin.settings"),
    children: [
      {
        label: "Profesionales",
        href: "/admin/especialidades",
        icon: Briefcase,
        permissionsAny: adminNavPermission("admin.settings.professionals"),
        children: [
          {
            label: "Especialidades",
            href: "/admin/especialidades",
            icon: GraduationCap,
            permissionsAny: adminNavPermission("admin.settings.specialties"),
          },
          {
            label: "Técnicos",
            href: "/admin/tecnico-laboral",
            icon: UserRound,
            permissionsAny: adminNavPermission("admin.settings.labor_technician"),
          },
        ],
      },
      {
        label: "Roles y permisos",
        href: "/admin/roles",
        icon: Shield,
        permissionsAny: adminNavPermission("admin.settings.roles"),
      },
      {
        label: "Equipos",
        href: "/admin/configuracion/equipos",
        icon: Users,
        permissionsAny: adminNavPermission("admin.settings.teams"),
      },
      {
        label: "Referidos",
        href: "/admin/configuracion/referidos",
        icon: Gift,
        permissionsAny: adminNavPermission("admin.settings.referrals"),
      },
      {
        label: "Global",
        href: "/admin/configuracion",
        icon: Globe2,
        permissionsAny: adminNavPermission("admin.settings.global"),
      },
      {
        label: "Pasarelas",
        href: "/admin/gateway-configs",
        icon: CreditCard,
        permissionsAny: adminNavPermission("admin.settings.gateways"),
      },
    ],
  },
  {
    label: "Auditoría",
    href: "/admin/auditoria",
    icon: Shield,
    permissionsAny: adminNavPermission("admin.audit"),
  },
  {
    label: "Notificaciones",
    href: "/admin/notificaciones",
    icon: Bell,
    permissionsAny: adminNavPermission("admin.notifications"),
  },
  {
    label: "Ayuda",
    href: "/admin/ayuda",
    icon: HelpCircle,
    permissionsAny: adminNavPermission("admin.help"),
  },
];
