import {
  Building2,
  CheckCircle2,
  ClipboardCheck,
  CreditCard,
  FileBarChart2,
  Gift,
  Globe2,
  HelpCircle,
  Home,
  Layers,
  Map,
  Package,
  Receipt,
  Settings,
  Shield,
  ShoppingCart,
  Bell,
  Users,
  Stethoscope,
  UserRound,
  UserCog,
  XCircle,
  GraduationCap,
} from "lucide-react";
import type { NavItem } from "@/components/layout/nav-items";

/** Nav alineada al mockup PIEL360 backoffice (rutas reales + stubs UI). */
export const adminNav: NavItem[] = [
  {
    label: "Panel de control",
    href: "/admin",
    icon: Home,
    roles: ["superadmin"],
  },
  {
    label: "Usuarios",
    href: "/admin/verificacion/usuarios",
    icon: Users,
    roles: ["monitor"],
  },
  {
    label: "Verificación (Pendientes)",
    href: "/admin/verificacion",
    icon: ClipboardCheck,
    roles: ["superadmin", "monitor"],
    badgeKey: "pending-verification",
  },
  {
    label: "Verificados",
    href: "/admin/verificacion/verificados",
    icon: CheckCircle2,
    roles: ["superadmin", "monitor"],
  },
  {
    label: "Rechazados",
    href: "/admin/verificacion/rechazados",
    icon: XCircle,
    roles: ["superadmin", "monitor"],
  },
  {
    label: "Empresas aliadas",
    href: "/admin/verificacion/empresas-aliadas",
    icon: Building2,
    roles: ["monitor"],
  },
  {
    label: "Reportes",
    href: "/admin/verificacion/reportes",
    icon: FileBarChart2,
    roles: ["monitor"],
  },
  {
    label: "Configuración",
    href: "/admin/verificacion/configuracion",
    icon: Settings,
    roles: ["monitor"],
  },
  {
    label: "Moderadores",
    href: "/admin/moderadores",
    icon: UserCog,
    roles: ["superadmin"],
  },
  {
    label: "Mapas",
    href: "/admin/mapa",
    icon: Map,
    roles: ["superadmin"],
    children: [
      { label: "Médicos", href: "/admin/mapa/medicos", icon: Stethoscope },
      { label: "Pacientes", href: "/admin/mapa/pacientes", icon: UserRound },
    ],
  },
  {
    label: "Empresas",
    href: "/admin/empresas",
    icon: Building2,
    roles: ["superadmin"],
  },
  {
    label: "Usuarios",
    href: "/admin/usuarios",
    icon: Users,
    roles: ["superadmin"],
  },
  {
    label: "Bolsa de unidades",
    href: "/admin/bolsa-unidades",
    icon: Package,
    roles: ["superadmin"],
  },
  {
    label: "Planes",
    href: "/admin/planes",
    icon: Layers,
    roles: ["superadmin"],
  },
  {
    label: "Compras y transacciones",
    href: "/admin/compras",
    icon: ShoppingCart,
    roles: ["superadmin"],
  },
  {
    label: "Reportes",
    href: "/admin/reportes",
    icon: FileBarChart2,
    roles: ["superadmin"],
  },
  {
    label: "Facturación",
    href: "/admin/facturacion",
    icon: Receipt,
    roles: ["superadmin"],
  },
  {
    label: "Doctores",
    href: "/admin/doctores",
    icon: Stethoscope,
    roles: ["superadmin"],
  },
  {
    label: "Pacientes",
    href: "/admin/pacientes",
    icon: UserRound,
    roles: ["superadmin"],
  },
  {
    label: "Suscripciones",
    href: "/admin/suscripciones",
    icon: CreditCard,
    roles: ["superadmin"],
  },
  {
    label: "Configuración",
    href: "/admin/configuracion",
    icon: Settings,
    roles: ["superadmin"],
    children: [
      {
        label: "Roles y permisos",
        href: "/admin/roles",
        icon: Shield,
      },
      {
        label: "Especialidades",
        href: "/admin/especialidades",
        icon: GraduationCap,
      },
      {
        label: "Permisos de planes",
        href: "/admin/roles/permisos-planes",
        icon: Layers,
      },
      {
        label: "Equipos",
        href: "/admin/configuracion/equipos",
        icon: Users,
      },
      {
        label: "Referidos",
        href: "/admin/configuracion/referidos",
        icon: Gift,
      },
      {
        label: "Global",
        href: "/admin/configuracion",
        icon: Globe2,
      },
    ],
  },
  {
    label: "Auditoría",
    href: "/admin/auditoria",
    icon: Shield,
    roles: ["superadmin"],
  },
  {
    label: "Notificaciones",
    href: "/admin/notificaciones",
    icon: Bell,
    roles: ["superadmin"],
  },
  {
    label: "Ayuda",
    href: "/admin/ayuda",
    icon: HelpCircle,
    roles: ["superadmin"],
  },
];
